### ISSUE TITLE
Deps

### ISSUE THREAD

**Issue by gedw99** [mearaj/gio-video#1]
Hey @mearaj 

Wow this is really great stuff.

There is a ffmpeg downloader in golang to make it easier for devs if your interested: https://github.com/stashapp/stash/blob/develop/internal/manager/task/download_ffmpeg.go

Do you think this will work on Mobile ? 
https://github.com/gioui-plugins/gio-plugins/issues/25#issuecomment-2159805667

**Comment by mearaj** [comment]
Hi @gedw99,
I actually don't know whether it will work or not.
Also I remember the license issue related to [ffmpeg LGPL v2.1+](https://github.com/FFmpeg/FFmpeg/blob/master/LICENSE.md).
I am currently unable to maintain this repo.
I remember there were not good alternatives during those time, don't know
whether there are any today.
I also do remember that most lenient license projects were v8, v9 and av1 in c language
and it was possible to integrate with cgo (but with still lot of work).

**Comment by gedw99** [comment]
OK good to know..

I will see how it goes in Gio-plugins. Might be able to get one going there now that the gio cmd things are now working.
